'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Perguntas.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apresentacao1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apresentacao1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apresentacao2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apresentacao2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apresentacao8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apresentacao8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apresentacao9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apresentacao9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao10() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao10", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao11() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao11", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao12() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao12", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao13() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao13", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao14() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao14", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao15() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao15", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao16() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao16", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao17() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao17", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao18() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao18", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao18_2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao18_2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao19() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao19", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao20() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao20", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao21() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao21", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao22() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao22", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao22_1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao22_1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao23() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao23", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao23_2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao23_2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao24() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao24", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao24_2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao24_2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao5_2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao5_2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao6() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao6", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao6_2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao6_2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao7() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao7", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao7_2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao7_2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao8() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao8", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property audioApresentacao9() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("audioApresentacao9", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_7_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_7_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_apresentacao7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_apresentacao7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_musica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_musica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao_novo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao_novo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balao9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balao9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property beijo_me_liga() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("beijo_me_liga", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bln2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bln2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bln3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bln3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imagem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imagem2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagem2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imagem3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagem3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img_fechar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_fechar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property palavras_lexicais() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("palavras_lexicais", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
